version: '2.4'
services:

  ## Consultation ##
  consultation-service:
    container_name: 'db-exam-consultation-service'
    build: 
      context: ../DBD-Exam-Project
      dockerfile: ConsultationService/Dockerfile.compose
    hostname: db-exam-consultation-service
    mem_limit: 400m
    memswap_limit: 6000m
    ports:
      - 18080:80
    restart: always
    


networks:
  default:
    external:
      name: db-exam