version: '3.8'
services:

  ## Consultation ##
  consultation-service:
    container_name: 'db-exam-consultation-service'
    build: 
      context: ../DBD-Exam-Project
      dockerfile: ConsultationService/Dockerfile.compose
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - 18090:80
    restart: always


  ## Mail-Service ##
  mail-service:
    container_name: 'db-exam-mail-service'
    build: 
      context: ../DBD-Exam-Project
      dockerfile: MailService/Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - 18092:80
    restart: always

  ## Prescription-Service ##
  prescription-service:
    container_name: 'db-exam-prescription-service'
    build: 
      context: ../DBD-Exam-Project
      dockerfile: PrescriptionService/Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - 18093:80
    restart: always

  ## TestData-Service ##
  testdata-service:
    container_name: 'db-exam-testdata-service'
    build: 
      context: ../DBD-Exam-Project
      dockerfile: TestDataAPI/Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - 18094:80
    restart: always

  ## CronJob-Service ##
  cronjob-service:
    container_name: 'db-exam-cronjob-service'
    build: 
      context: ../DBD-Exam-Project
      dockerfile: CronJobService/Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - 18095:80
    restart: always

networks:
  default:
    name: db-exam
