version: '3'
services:

## PG Admin ##
  pgadmin:
    container_name: db-exam-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "10010:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - ./postgres/pgadmin-servers.json:/pgadmin4/servers.json # preconfigured servers/connections

## Mongo Express ##
  mongo-express:
    container_name: db-exam-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 10020:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopw
      ME_CONFIG_MONGODB_URL: mongodb://mongo-router:27017/


## Redis Insight ##

  redis-insight:
    container_name: db-exam-redis-insight
    image: redislabs/redisinsight
    ports:
      - 10030:8001

networks:
  default:
    name: db-exam