version: '2.4'
services:

  ## Postgres ##
  postgres:
    container_name: 'db-exam-consultation-service'
    build: 
      context: ../DBD-Exam-Project/ConsulationService
      dockerfile: Dockerfile
    hostname: db-exam-consultation-service
    mem_limit: 400m
    memswap_limit: 6000m
    ports:
      - 15432:5432
    restart: always
    


networks:
  default:
    external:
      name: db-exam